name: Deploy to AWS S3

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: pip install mkdocs
      - run: pip install mkdocs-material
      - run: mkdocs build
      - uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: "${{ secrets.AWS_ACCESS_KEY }}"
          aws_secret_access_key: "${{ secrets.AWS_SECRET_KEY }}"
          aws_bucket: "${{ secrets.AWS_BUCKET }}"
          source_dir: site