apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-pipeline
spec:
  workspaces:
    - name: shared-data
    - name: dockerconfig
  params:
    - name: source-url
      description: The URL of the source to build
    - name: source-revision
      description: The revision of the source to build
    - name: app-name
      description: The name of the app to build
  tasks:
    - name: fetch-source
      taskRef:
        name: git-clone
      params:
        - name: url
          value: $(params.source-url)
        - name: deleteExisting
          value: "true"
      workspaces:
      - name: output
        workspace: shared-data
    - name: build-image
      taskRef:
        name: buildpacks
      runAfter:
        - fetch-source
      workspaces:
        - name: source
          workspace: shared-data
        - name: dockerconfig
          workspace: dockerconfig
      params:
      - name: APP_IMAGE
        value: docker.io/matheuscruzdev/$(params.app-name)
      - name: BUILDER_IMAGE
        value: heroku/buildpacks:20